spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
      hikari:
        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
        username: sa
  h2:
    console:
      enabled: true

  profiles:
    group:
      local: oauth
      real: real, real-db, oauth

  session:
    store-type: jdbc
