spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
  datasource:
      hikari:
        jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  h2:
    console:
      enabled: true